FROM ubuntu:24.04

RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

COPY ./assetx-node-bin /usr/local/bin/node
RUN chmod +x /usr/local/bin/node
EXPOSE 9944 9933
ENTRYPOINT ["/usr/local/bin/node"]
