
//! Autogenerated weights for `pallet_incentive`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 49.0.0
//! DATE: 2026-01-15, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `guozheng-VMware-Virtual-Platform`, CPU: `13th Gen Intel(R) Core(TM) i7-13650HX`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/solochain-template-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_incentive
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/incentive/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_incentive`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::pallet::WeightInfo for WeightInfo<T> {
	/// Storage: `Incentive::IncentivePoolReleased` (r:1 w:1)
	/// Proof: `Incentive::IncentivePoolReleased` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Incentive::IncentivePoolReserved` (r:1 w:1)
	/// Proof: `Incentive::IncentivePoolReserved` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn trigger_dynamic_release() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `184`
		//  Estimated: `3593`
		// Minimum execution time: 18_530_000 picoseconds.
		Weight::from_parts(20_669_000, 0)
			.saturating_add(Weight::from_parts(0, 3593))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Incentive::Asset30dTradeCount` (r:1 w:0)
	/// Proof: `Incentive::Asset30dTradeCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Incentive::IncentivePoolReleased` (r:1 w:0)
	/// Proof: `Incentive::IncentivePoolReleased` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Incentive::IncentivePoolUsed` (r:1 w:1)
	/// Proof: `Incentive::IncentivePoolUsed` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0x6173736574732f01010101010101010101010101010101010101010101010101` (r:1 w:0)
	/// Proof: UNKNOWN KEY `0x6173736574732f01010101010101010101010101010101010101010101010101` (r:1 w:0)
	fn distribute_quality_data_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `803`
		//  Estimated: `6196`
		// Minimum execution time: 47_527_000 picoseconds.
		Weight::from_parts(52_928_000, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Incentive::MarketMonthlyVolume` (r:0 w:1)
	/// Proof: `Incentive::MarketMonthlyVolume` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn register_market_monthly_volume() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_820_000 picoseconds.
		Weight::from_parts(3_158_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Incentive::GovernanceVotingWeight` (r:0 w:1)
	/// Proof: `Incentive::GovernanceVotingWeight` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn register_voting_weight() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_924_000 picoseconds.
		Weight::from_parts(3_335_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
