
//! Autogenerated weights for `pallet_dataassets`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 49.0.0
//! DATE: 2026-03-20, STEPS: `10`, REPEAT: `5`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `guozheng-VMware-Virtual-Platform`, CPU: `13th Gen Intel(R) Core(TM) i7-13650HX`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/solochain-template-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_dataassets
// --extrinsic
// register_asset_under_load
// --steps
// 10
// --repeat
// 5
// --output
// ./pallets/dataassets/src/weights_load.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_dataassets`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_dataassets::WeightInfo for WeightInfo<T> {
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Incentive::HasFirstCreateReward` (r:1 w:0)
	/// Proof: `Incentive::HasFirstCreateReward` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Incentive::IncentivePoolReleased` (r:1 w:0)
	/// Proof: `Incentive::IncentivePoolReleased` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Incentive::IncentivePoolUsed` (r:1 w:0)
	/// Proof: `Incentive::IncentivePoolUsed` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `DataAssets::AssetCollateral` (r:0 w:1)
	/// Proof: `DataAssets::AssetCollateral` (`max_values`: None, `max_size`: Some(261), added: 2736, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0x6173736574732f1c3cfa48421c340e0caa8f33f9c52fa6fe15b2a1902d8277a1` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x6173736574732f1c3cfa48421c340e0caa8f33f9c52fa6fe15b2a1902d8277a1` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x5f6d657461646174612f6e6578745f746f6b656e5f6964` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x5f6d657461646174612f6e6578745f746f6b656e5f6964` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x5f6d657461646174612f746f6b656e5f6d617070696e67732f00000000` (r:0 w:1)
	/// Proof: UNKNOWN KEY `0x5f6d657461646174612f746f6b656e5f6d617070696e67732f00000000` (r:0 w:1)
	/// Storage: UNKNOWN KEY `0x5f696e6974` (r:0 w:1)
	/// Proof: UNKNOWN KEY `0x5f696e6974` (r:0 w:1)
	/// The range of component `x` is `[10000, 100000]`.
	fn register_asset_under_load(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `405`
		//  Estimated: `3992`
		// Minimum execution time: 131_480_000 picoseconds.
		Weight::from_parts(151_601_555, 0)
			.saturating_add(Weight::from_parts(0, 3992))
			// Standard Error: 60
			.saturating_add(Weight::from_parts(136, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(6))
	}
}
