//! Autogenerated weights for pallet_dataassets
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: (will be filled by benchmark)
//! 
//! HOSTNAME: (will be filled by benchmark)
//! CPU: (will be filled by benchmark)
//! 
//! SHORT-NAME: `pallet_dataassets`, LONG-NAME: `pallet-dataassets`, RUNTIME: `Development`
//! WARMUPS: `10`, REPEAT: `20`
//! WEIGHT-PATH: `pallets/dataassets/src/`
//! WEIGHT-METRIC: `Average`, WEIGHT-MUL: `1.0`, WEIGHT-ADD: `0`

// Executed Command:
// (will be filled by benchmark)

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_dataassets.
pub trait WeightInfo {
    fn register_asset() -> Weight;
    fn issue_certificate() -> Weight;
    fn transfer_asset() -> Weight;
    fn revoke_certificate() -> Weight;
    fn lock_asset() -> Weight;
    fn unlock_asset() -> Weight;
    fn slash_collateral() -> Weight;
    fn authorize_operator() -> Weight;
    fn revoke_authorization() -> Weight;
}

/// Weights for pallet_dataassets using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: DataAssets AssetCollateral (r:1 w:1)
    /// Proof: DataAssets AssetCollateral (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
    fn register_asset() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `3593`
        // Minimum execution time: 50_000 picoseconds.
        Weight::from_parts(60_000_000, 3593)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }

    fn issue_certificate() -> Weight {
        Weight::from_parts(45_000_000, 3593)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }

    fn transfer_asset() -> Weight {
        Weight::from_parts(40_000_000, 2603)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }

    fn revoke_certificate() -> Weight {
        Weight::from_parts(35_000_000, 2603)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }

    fn lock_asset() -> Weight {
        Weight::from_parts(30_000_000, 2603)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    fn unlock_asset() -> Weight {
        Weight::from_parts(30_000_000, 2603)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    fn slash_collateral() -> Weight {
        Weight::from_parts(35_000_000, 2603)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }

    fn authorize_operator() -> Weight {
        Weight::from_parts(25_000_000, 2603)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    fn revoke_authorization() -> Weight {
        Weight::from_parts(20_000_000, 2603)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
    fn register_asset() -> Weight {
        Weight::from_parts(60_000_000, 3593)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(4_u64))
    }

    fn issue_certificate() -> Weight {
        Weight::from_parts(45_000_000, 3593)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }

    fn transfer_asset() -> Weight {
        Weight::from_parts(40_000_000, 2603)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }

    fn revoke_certificate() -> Weight {
        Weight::from_parts(35_000_000, 2603)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }

    fn lock_asset() -> Weight {
        Weight::from_parts(30_000_000, 2603)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn unlock_asset() -> Weight {
        Weight::from_parts(30_000_000, 2603)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn slash_collateral() -> Weight {
        Weight::from_parts(35_000_000, 2603)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }

    fn authorize_operator() -> Weight {
        Weight::from_parts(25_000_000, 2603)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn revoke_authorization() -> Weight {
        Weight::from_parts(20_000_000, 2603)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
}
