
//! Autogenerated weights for `pallet_dataassets`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 49.0.0
//! DATE: 2026-01-12, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `guozheng-VMware-Virtual-Platform`, CPU: `13th Gen Intel(R) Core(TM) i7-13650HX`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/solochain-template-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_dataassets
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/dataassets/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;


/// Weight functions for `pallet_dataassets`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::pallet::WeightInfo for WeightInfo<T> {
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Incentive::HasFirstCreateReward` (r:1 w:0)
	/// Proof: `Incentive::HasFirstCreateReward` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Incentive::IncentivePoolReleased` (r:1 w:0)
	/// Proof: `Incentive::IncentivePoolReleased` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Incentive::IncentivePoolUsed` (r:1 w:0)
	/// Proof: `Incentive::IncentivePoolUsed` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `DataAssets::AssetCollateral` (r:0 w:1)
	/// Proof: `DataAssets::AssetCollateral` (`max_values`: None, `max_size`: Some(261), added: 2736, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0x6173736574732fc008023d5802a250b3ad74741b8ba83cd40ecb3a9db0b03072` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x6173736574732fc008023d5802a250b3ad74741b8ba83cd40ecb3a9db0b03072` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x5f6d657461646174612f6e6578745f746f6b656e5f6964` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x5f6d657461646174612f6e6578745f746f6b656e5f6964` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x5f6d657461646174612f746f6b656e5f6d617070696e67732f00000000` (r:0 w:1)
	/// Proof: UNKNOWN KEY `0x5f6d657461646174612f746f6b656e5f6d617070696e67732f00000000` (r:0 w:1)
	/// Storage: UNKNOWN KEY `0x5f696e6974` (r:0 w:1)
	/// Proof: UNKNOWN KEY `0x5f696e6974` (r:0 w:1)
	fn register_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `118`
		//  Estimated: `3593`
		// Minimum execution time: 43_340_000 picoseconds.
		Weight::from_parts(62_584_000, 0)
			.saturating_add(Weight::from_parts(0, 3593))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `DataAssets::AssetApprovals` (r:1 w:0)
	/// Proof: `DataAssets::AssetApprovals` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0x3a6368696c645f73746f726167653a64656661756c743a3a6365727469666963` (r:0 w:1)
	/// Proof: UNKNOWN KEY `0x3a6368696c645f73746f726167653a64656661756c743a3a6365727469666963` (r:0 w:1)
	/// Storage: UNKNOWN KEY `0x6173736574732fe3d73b1b8d7f7d0801726064a02cf59dcd858332b0d073a935` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x6173736574732fe3d73b1b8d7f7d0801726064a02cf59dcd858332b0d073a935` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x5f6d657461646174612f6e6578745f746f6b656e5f6964` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x5f6d657461646174612f6e6578745f746f6b656e5f6964` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0xe6ef66d8243e6909eec0ac5b0ae04b0cf2da4043e0e03f68ce1dfde2b06a591f` (r:0 w:1)
	/// Proof: UNKNOWN KEY `0xe6ef66d8243e6909eec0ac5b0ae04b0cf2da4043e0e03f68ce1dfde2b06a591f` (r:0 w:1)
	fn issue_certificate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `626`
		//  Estimated: `4091`
		// Minimum execution time: 42_620_000 picoseconds.
		Weight::from_parts(56_824_000, 0)
			.saturating_add(Weight::from_parts(0, 4091))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `DataAssets::AssetApprovals` (r:0 w:1)
	/// Proof: `DataAssets::AssetApprovals` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0x6173736574732fe3d73b1b8d7f7d0801726064a02cf59dcd858332b0d073a935` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x6173736574732fe3d73b1b8d7f7d0801726064a02cf59dcd858332b0d073a935` (r:1 w:1)
	fn transfer_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `521`
		//  Estimated: `3986`
		// Minimum execution time: 21_530_000 picoseconds.
		Weight::from_parts(23_064_000, 0)
			.saturating_add(Weight::from_parts(0, 3986))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0x3a6368696c645f73746f726167653a64656661756c743a3a6365727469666963` (r:0 w:1)
	/// Proof: UNKNOWN KEY `0x3a6368696c645f73746f726167653a64656661756c743a3a6365727469666963` (r:0 w:1)
	/// Storage: UNKNOWN KEY `0x6173736574732fe3d73b1b8d7f7d0801726064a02cf59dcd858332b0d073a935` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x6173736574732fe3d73b1b8d7f7d0801726064a02cf59dcd858332b0d073a935` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0xe6ef66d8243e6909eec0ac5b0ae04b0cf2da4043e0e03f68ce1dfde2b06a591f` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0xe6ef66d8243e6909eec0ac5b0ae04b0cf2da4043e0e03f68ce1dfde2b06a591f` (r:1 w:1)
	fn revoke_certificate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `819`
		//  Estimated: `4284`
		// Minimum execution time: 32_591_000 picoseconds.
		Weight::from_parts(36_334_000, 0)
			.saturating_add(Weight::from_parts(0, 4284))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0x6173736574732fe3d73b1b8d7f7d0801726064a02cf59dcd858332b0d073a935` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x6173736574732fe3d73b1b8d7f7d0801726064a02cf59dcd858332b0d073a935` (r:1 w:1)
	fn lock_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `521`
		//  Estimated: `3986`
		// Minimum execution time: 13_696_000 picoseconds.
		Weight::from_parts(15_123_000, 0)
			.saturating_add(Weight::from_parts(0, 3986))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0x6173736574732fe3d73b1b8d7f7d0801726064a02cf59dcd858332b0d073a935` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x6173736574732fe3d73b1b8d7f7d0801726064a02cf59dcd858332b0d073a935` (r:1 w:1)
	fn unlock_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `521`
		//  Estimated: `3986`
		// Minimum execution time: 12_558_000 picoseconds.
		Weight::from_parts(14_536_000, 0)
			.saturating_add(Weight::from_parts(0, 3986))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `DataAssets::AssetCollateral` (r:1 w:1)
	/// Proof: `DataAssets::AssetCollateral` (`max_values`: None, `max_size`: Some(261), added: 2736, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn slash_collateral() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `336`
		//  Estimated: `3726`
		// Minimum execution time: 27_879_000 picoseconds.
		Weight::from_parts(39_855_000, 0)
			.saturating_add(Weight::from_parts(0, 3726))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `DataAssets::AssetApprovals` (r:1 w:1)
	/// Proof: `DataAssets::AssetApprovals` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0x6173736574732fe3d73b1b8d7f7d0801726064a02cf59dcd858332b0d073a935` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x6173736574732fe3d73b1b8d7f7d0801726064a02cf59dcd858332b0d073a935` (r:1 w:1)
	fn authorize_operator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `564`
		//  Estimated: `4029`
		// Minimum execution time: 22_116_000 picoseconds.
		Weight::from_parts(25_285_000, 0)
			.saturating_add(Weight::from_parts(0, 4029))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `DataAssets::AssetApprovals` (r:1 w:1)
	/// Proof: `DataAssets::AssetApprovals` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0x6173736574732fe3d73b1b8d7f7d0801726064a02cf59dcd858332b0d073a935` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x6173736574732fe3d73b1b8d7f7d0801726064a02cf59dcd858332b0d073a935` (r:1 w:1)
	fn revoke_authorization() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `666`
		//  Estimated: `4131`
		// Minimum execution time: 21_666_000 picoseconds.
		Weight::from_parts(26_073_000, 0)
			.saturating_add(Weight::from_parts(0, 4131))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
}
